WITH TOTAL_COUNT AS (
	SELECT COUNT(*) AS TOTAL_COUNT
	FROM ASSETS a 
)
SELECT Q.* , TOTAL_COUNT.TOTAL_COUNT , ROUND(CAST(Q.COUNT as decimal) / TOTAL_COUNT.TOTAL_COUNT, 3) AS PERCENT
FROM (
	SELECT 
		CASE 
			WHEN arl.ASSET_PRECINCT IS NOT NULL THEN 1
			ELSE 0
		END AS ASSET_PRECINCT_EXTRACTED , 
		CASE 
			WHEN arl.ROUTER_ID IS NOT NULL THEN 1
			ELSE 0
		END AS ROUTER_PRECINCT_MATCH , 
		CASE 
			WHEN arl.ROUTER_LOCATION_LATITUDE IS NOT NULL AND ARL.ROUTER_LOCATION_LONGITUDE IS NOT NULL THEN 1
			ELSE 0
		END AS ROUTER_LAT_LONG_EXISTS , 
		COUNT(*) AS COUNT
	FROM ASSET_ROUTER_LOCATIONS arl , TOTAL_COUNT
	GROUP BY 
		CASE 
			WHEN arl.ASSET_PRECINCT IS NOT NULL THEN 1
			ELSE 0
		END , 
		CASE 
			WHEN arl.ROUTER_ID IS NOT NULL THEN 1
			ELSE 0
		END , 
		CASE 
			WHEN arl.ROUTER_LOCATION_LATITUDE IS NOT NULL AND ARL.ROUTER_LOCATION_LONGITUDE IS NOT NULL THEN 1
			ELSE 0
		END 
	) Q , 
	TOTAL_COUNT
ORDER BY Q.ASSET_PRECINCT_EXTRACTED DESC , Q.ROUTER_PRECINCT_MATCH DESC , Q.ROUTER_LAT_LONG_EXISTS DESC; 

SELECT arl.*
FROM ASSET_ROUTER_LOCATIONS arl 
WHERE arl.ASSET_ID  IN 
(
	SELECT arl.ASSET_ID
	FROM ASSET_ROUTER_LOCATIONS arl 
	GROUP BY arl.ASSET_ID 
	HAVING count(*) > 1
); 

SELECT Q.ITEMCLASS, COUNT(*)
FROM (
	SELECT DISTINCT ah.ID , A.ITEMCLASS 
	FROM ASSET_HISTORY ah INNER JOIN ASSETS a ON AH.ID = A.ID 
	ORDER BY A.ITEMCLASS 
) q
GROUP BY Q.ITEMCLASS
ORDER BY Q.ITEMCLASS